name: Check if node20 is supported
description: Check if node20 is supported

inputs:
  container:
    type: string

outputs:
  supported:
    value: ${{ steps.node20.outputs.supported }}

runs:
  using: composite
  steps:
    - name: Check if node20 is Supported
      id: node20
      shell: bash
      run: |
        for platform in ubuntu:bionic centos:7 amazonlinux:2 alpine:3; do
          if [[ "${{ inputs.container }}" == "$platform" ]]; then
            echo "supported=false" >> $GITHUB_OUTPUT
            # https://github.com/actions/checkout/issues/1809
            echo "ACTIONS_RUNNER_FORCED_INTERNAL_NODE_VERSION=node16" >> $GITHUB_ENV
            echo "ACTIONS_RUNNER_FORCE_ACTIONS_NODE_VERSION=node16" >> $GITHUB_ENV
            # https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
            echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
            exit 0
          fi
        done
        echo "supported=true" >> $GITHUB_OUTPUT
