name: Upload Artifacts to S3
description: |
  Uploads module artifacts to S3 bucket.

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  osnick:
    description: 'OS Nickname'
    required: false
    default: ''
  github-ref: 
    description: 'github ref'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Configure AWS credentials and upload artifcats # todo - use aws role instead
      shell: bash
      run: |
          echo ::group::install aws cli
          python3 -m venv .aws-cli-venv && source .aws-cli-venv/bin/activate &&
          pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
          echo ::endgroup::

          # Variables from the workflow
          export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
          export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
          export AWS_REGION="us-east-1"
          # Check if the required environment variables are set
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
            echo "Missing AWS credentials or region configuration."
            exit 1
          fi
          # Configure AWS CLI with provided credentials and region
          echo "Configuring AWS CLI with access keys..."
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

          echo ::group::upload artifacts
            SNAPSHOT=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
          echo ::endgroup::
          echo ::group::upload staging release
            RELEASE=1 SHOW=1 STAGING=1 VERBOSE=1 ./sbin/upload-artifacts
          echo ::endgroup::
          
          echo ::group::upload production release
            REF="${{ inputs.github-ref }}"
            PATTERN="refs/tags/v[0-9]+.*"
            if [[ $REF =~ $PATTERN ]]; then
              RELEASE=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            fi
          echo ::endgroup::
