name: Upload Artifacts to S3
description: |
  Uploads module artifacts to S3 bucket.

inputs:
  aws-access-key-id:
    description: 'AWS Access Key ID'
    required: true
  aws-secret-access-key:
    description: 'AWS Secret Access Key'
    required: true
  osnick:
    description: 'OS Nickname'
    required: false
    default: ''
  github-ref: 
    description: 'github ref'
    required: false
    default: ''
  beta-version:
    description: 'Beta version for S3 uploads'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Configure AWS credentials and upload artifcats # todo - use aws role instead
      shell: bash
      run: |
          echo ::group::install aws cli
          python3 -m venv .aws-cli-venv && source .aws-cli-venv/bin/activate &&
          pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
          echo ::endgroup::

          # Variables from the workflow
          export AWS_ACCESS_KEY_ID="${{ inputs.aws-access-key-id }}"
          export AWS_SECRET_ACCESS_KEY="${{ inputs.aws-secret-access-key }}"
          export AWS_REGION="us-east-1"
          # Check if the required environment variables are set
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_REGION" ]; then
            echo "Missing AWS credentials or region configuration."
            exit 1
          fi
          # Configure AWS CLI with provided credentials and region
          echo "Configuring AWS CLI with access keys..."
          aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
          aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
          aws configure set region "$AWS_REGION"

          echo ::group::upload artifacts
            # For nightly/beta builds, upload snapshots; for release builds, upload both
            if [[ -n "${{ inputs.beta-version }}" ]]; then
              SNAPSHOT=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            else
              SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            fi
          echo ::endgroup::
          echo ::group::upload staging release
            if [[ -n "${{ inputs.beta-version }}" ]]; then
              STAGING=1 SNAPSHOT=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            else
              STAGING=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            fi
          echo ::endgroup::
          
          echo ::group::upload production release
            REF="${{ inputs.github-ref }}"
            PATTERN="refs/tags/v[0-9]+.*"
            if [[ $REF =~ $PATTERN ]]; then
              echo "This is a tagged build"
              RELEASE=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
            fi
          echo ::endgroup::
          
          echo ::group::upload to beta folder with version
            # Use provided beta version if available
            if [[ -n "${{ inputs.beta-version }}" ]]; then
              BETA_VERSION="${{ inputs.beta-version }}"
              echo "Using provided beta version: ${BETA_VERSION}"
              
              # Create copies with beta version name and move to artifacts/ (not snapshots/)
              # This ensures upload goes to s3://.../beta/ not s3://.../beta/snapshots/
              cd bin/artifacts/snapshots
              for file in rejson-oss.*.zip rejson-oss.*.tgz; do
                if [[ -f "$file" ]]; then
                  # Replace branch name with beta version in filename
                  # e.g., rejson-oss.Linux-rhel9-x86_64.fixS3Upload.zip -> rejson-oss.Linux-rhel9-x86_64.99.99.99.20251120.162724.560.zip
                  beta_file=$(echo "$file" | sed "s/\.\([^.]*\)\.\(zip\|tgz\)$/.$BETA_VERSION.\2/")
                  cp "$file" "../$beta_file"
                  echo "Created beta version: $beta_file"
                fi
              done
              cd ../../..
              
              # Upload to beta folder (without /snapshots/ subdirectory, so use SNAPSHOT=0)
              export BETA_VERSION="${BETA_VERSION}"
              BETA=1 SHOW=1 VERBOSE=1 ./sbin/upload-artifacts
              
              # Clean up beta-versioned copies from artifacts/
              cd bin/artifacts
              for file in rejson-oss.*.$BETA_VERSION.zip rejson-oss.*.$BETA_VERSION.tgz; do
                if [[ -f "$file" ]]; then
                  rm "$file"
                  echo "Cleaned up: $file"
                fi
              done
              cd ../..
            else
              echo "No beta version provided, skipping beta upload"
            fi
          echo ::endgroup::