name: Run pack module script

inputs:
  use-venv:
    default: '1'
    type: string
    

runs:
  using: composite
  steps:
    - name: Pack module
      shell: bash
      run: |
        if command -v scl_source &> /dev/null
        then
            . scl_source enable devtoolset-11 || true
        fi
        if [[ "${{inputs.use-venv}}" == "1" ]; then
          . venv/bin/activate
          git config --global --add safe.directory $GITHUB_WORKSPACE
          export PATH="$GITHUB_WORKSPACE/redis/src:$PATH"
          MODULE=$(realpath ./target/release/rejson.so) BRANCH=$TAG_OR_BRANCH \
            SHOW=1 OSNICK=${{ matrix.docker.nick }} ./sbin/pack.sh
        else
          make pack BRANCH=$TAG_OR_BRANCH
        fi
