name: Build JSON module and Redis Server
description: |
  Build JSON module and Redis Server

inputs:
  redis-ref:
    description: 'Redis version to build'
    required: true
    default: '7.2.1'
  san:
    type: string

runs:
  using: composite
  steps:
    - name: Build Redis
      shell: bash
      working-directory: redis
      run: |
        echo ::group::Build Redis
          make install -j `nproc`
        echo ::endgroup::
    - name: Build module
      shell: bash
      run: |
        echo ::group::Build RedisJSON
          . "$HOME/.cargo/env"
          make build SAN=${{ inputs.san }} -j `nproc`
        echo ::endgroup::