name: Pack the module and upload it to S3
description: Pack the module and upload it to S3

inputs:
  image: # The Docker image to use for the build
    description: 'The Docker image to use for the build'
    required: true

runs:
  using: composite
  steps:
    - name: Set Artifact Names
      # Artifact names have to be unique, so we base them on the environment.
      # We also remove invalid characters from the name.
      id: artifact-names
      shell: bash
      run: | # Invalid characters include: Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?
        echo "name=$(echo "${{ inputs.image }} x86-64, Redis unstable" | \
          sed -e 's/[":\/\\<>\|*?]/_/g' -e 's/__*/_/g' -e 's/^_//' -e 's/_$//')" >> $GITHUB_OUTPUT
    - name: Upload test artifacts
      if: inputs.image != 'amazonlinux:2' && inputs.image != 'ubuntu:bionic'
      uses: actions/upload-artifact@v4
      with:
        name: Test logs ${{ steps.artifact-names.outputs.name }}
        path: tests/**/logs/*.log*
        if-no-files-found: ignore
