name: Event CI

permissions:
  id-token: write
  contents: read

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare-values:
    runs-on: ubuntu-latest
    outputs:
      redis-ref: ${{ steps.set-env.outputs.redis-ref }}
    steps:
      - name: set env
        id: set-env
        run: |
          echo "redis-ref=unstable" >> $GITHUB_OUTPUT  # todo change per version/tag
  linux:
    uses: ./.github/workflows/flow-linux-x86.yml
    needs: [prepare-values]
    with:
      # os: jammy rocky9 amazonlinux2
      os: bionic focal jammy rocky8 rocky9 bullseye amazonlinux2 mariner2
      redis-ref: ${{needs.prepare-values.outputs.redis-ref}}
      run-test: false
    secrets: inherit
  ubuntu-arm64:
    uses: ./.github/workflows/flow-ubuntu-arm.yml
    needs: [prepare-values]
    with:
      redis-ref: ${{needs.prepare-values.outputs.redis-ref}}
      run-test: false
    secrets: inherit
  alpine:
    uses: ./.github/workflows/flow-alpine.yml
    needs: [prepare-values]
    with:
      redis-ref: ${{needs.prepare-values.outputs.redis-ref}}
      run-test: false
    secrets: inherit
  macos:
    uses: ./.github/workflows/flow-macos.yml
    needs: [prepare-values]
    with:
      redis-ref: ${{needs.prepare-values.outputs.redis-ref}}
      run-test: false
    secrets: inherit
  spellcheck:
    uses: ./.github/workflows/flow-spellcheck.yml
    secrets: inherit
  linter:
    uses: ./.github/workflows/flow-linter.yml
    secrets: inherit
